### ISSUE TITLE
[Bug] Coqui-ai TTS in Jenkins job key = winreg.OpenKey( ... FileNotFoundError

### ISSUE THREAD

**Issue by LeszekChojnacki** [coqui-ai/TTS#4291]
### Describe the bug

Trying to use Coqui-ai TTS in Jenkins job, and Im getting below err:

`C:\ProgramData\Jenkins\.jenkins\workspace\Dziennik\scripts>python tts.py --input_text_file_path DU/2025/658 
Traceback (most recent call last):
  File "C:\ProgramData\Jenkins\.jenkins\workspace\Dziennik\scripts\tts.py", line 34, in <module>
    api = TTS(model_name="tts_models/pl/mai_female/vits")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ja\AppData\Local\Programs\Python\Python311\Lib\site-packages\TTS\api.py", line 64, in __init__
    self.manager = ModelManager(models_file=self.get_models_file_path(), progress_bar=progress_bar, verbose=False)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ja\AppData\Local\Programs\Python\Python311\Lib\site-packages\TTS\utils\manage.py", line 51, in __init__
    self.output_prefix = get_user_data_dir("tts")
                         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ja\AppData\Local\Programs\Python\Python311\Lib\site-packages\TTS\utils\generic_utils.py", line 139, in get_user_data_dir
    key = winreg.OpenKey(
          ^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] Nie mo�na odnale�� okre�lonego pliku`

This is the code which i use:

`from TTS.api import TTS
import torch
import io
import argparse

# arg parser
parser = argparse.ArgumentParser()
parser.add_argument('--input_text_file_path', dest='input_text_file_path',
                    type=str, help='Add input_text_file_path')
args = parser.parse_args()

# Save the original torch.load function
_original_torch_load = torch.load

# Define a new function that forces weights_only=False

def custom_torch_load(*args, **kwargs):
    if "weights_only" not in kwargs:
        kwargs["weights_only"] = False
    return _original_torch_load(*args, **kwargs)

# Override torch.load globally
torch.load = custom_torch_load

def import_text_file(file_name):
    with io.open(f"{file_name}.txt", 'r', encoding="utf-8") as file:
        return file.read().replace('\n', '')

# TTS with on the fly voice conversion
api = TTS(model_name="tts_models/pl/mai_female/vits")
api.tts_to_file(
    text=import_text_file(args.input_text_file_path.replace('/', '_')),
    speaker_wav="target/speaker.wav",
    file_path=f"{args.input_text_file_path.replace('/', '_')}.wav"
)`

At the same time the code is working normally when i trigger it from the cmd, just when i use jenkins the issue show up.

Not able to find any proper workaround for this.

### To Reproduce

.

### Logs

```shell

```

### Environment

```shell
TTS 0.22.0
```

**Comment by eginhard** [comment]
Can you try with [our fork](https://github.com/idiap/coqui-ai-TTS) (available via `pip install coqui-tts`)? This repo is not maintained anymore. In the fork you also don't need to overwrite `torch.load()`, it is already fixed there.

**Comment by LeszekChojnacki** [comment]
@eginhard thanks for your feedback, after testing can see that that im getting the same err. I have complitly delted the py from my local machin and recreated the whole stack with your fork, and still getting the same err.

This is the methond which is triggering the err:

`
def get_user_data_dir(appname: str) -> Path:
    TTS_HOME = os.environ.get("TTS_HOME")
    XDG_DATA_HOME = os.environ.get("XDG_DATA_HOME")
    if TTS_HOME is not None:
        ans = Path(TTS_HOME).expanduser().resolve(strict=False)
    elif XDG_DATA_HOME is not None:
        ans = Path(XDG_DATA_HOME).expanduser().resolve(strict=False)
    elif sys.platform == "win32":
        import winreg  # pylint: disable=import-outside-toplevel
        key = winreg.OpenKey(
            winreg.HKEY_CURRENT_USER, r"Software\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders"
        )
        dir_, _ = winreg.QueryValueEx(key, "Local AppData")
        ans = Path(dir_).resolve(strict=False)
    elif sys.platform == "darwin":
        ans = Path("~/Library/Application Support/").expanduser()
    else:
        ans = Path.home().joinpath(".local/share")
    return ans.joinpath(appname)
`

So I have c**hange this check elif sys.platform == "win32" to elif sys.platform == "win32.",** and the code skips the problematic place and works 

I know this is a super dirty solution but I was not able to find a better solution.

**Comment by eginhard** [comment]
Ok, thanks for checking! I'm not familiar with Windows or Jenkins, so no idea why this occurs unfortunately. 

As a cleaner workaround that does not require patching any code, I'd recommend to manually set the `TTS_HOME` or `XDG_DATA_HOME` environment variable with the folder where you want to store your Coqui models (see https://coqui-tts.readthedocs.io/en/latest/faq.html#where-does-coqui-store-downloaded-models). When either of these is set, the other branches in that if-statement will be skipped, avoiding the error.
